server:
  port: 8080
spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
app:
  build:
    version: ^project.version^
  sdhubId: BPNL000000000000
  custodianWallet:
    uri: https://managed-identity-wallets.int.demo.catena-x.net/api
    auth-server-url: https://centralidp.demo.catena-x.net/auth
    realm: CX-Central
    clientId: ${CLIENTID}
    clientSecret: ${CLIENTSECRET}
