server:
  port: 8080
spring:
  data:
    mongodb:
      host:  mongodb-sdhub-pen
      port: 27017
      database: sdhub-mongo
app:
  build:
    version: ^project.version^
  sdhubId: BPNL000000000000
  custodianWallet:
    uri: https://managed-identity-wallets-pen.dev.demo.catena-x.net/api
    auth-server-url: https://centralidp-pen.dev.demo.catena-x.net/auth
    realm: CX-Central
    clientId: ${CLIENTID}
    clientSecret: ${CLIENTSECRET}
  db:
    sd:
      collectionName: selfdescription
