server:
  port: 8080
spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
keycloak:
  auth-server-url: https://centralidp.demo.catena-x.net/auth
  realm: CX-Central
  resource: Cl2-CX-Portal
  bearer-only: true
  use-resource-role-mappings: true
  principal-attribute: preferred_username
app:
  build:
    version: ^project.version^
  verifiableCredentials:
    durationDays: 90
    idPrefix: http://sdhub.int.demo.catena-x.net/
  custodianWallet:
    uri: https://managed-identity-wallets.int.demo.catena-x.net/api
    auth-server-url: https://centralidp.demo.catena-x.net/auth
    realm: CX-Central
    clientId: ${CLIENTID}
    clientSecret: ${CLIENTSECRET}
  security:
    createRole: add_self_descriptions
    deleteRole: delete_tech_user_management
