server:
  port: 8080
spring:
  data:
    mongodb:
      host: mongodb-sdhub
      port: 27017
      database: sdhub-mongo
keycloak:
  auth-server-url: https://centralidp-pen.dev.demo.catena-x.net/auth
  realm: CX-Central
  resource: Cl2-CX-Portal
  bearer-only: true
  use-resource-role-mappings: true
  principal-attribute: preferred_username
app:
  build:
    version: ^project.version^
  verifiableCredentials:
    durationDays: 90
    idPrefix: http://sdhub.int.demo.catena-x.net/
  custodianWallet:
    uri: https://managed-identity-wallets-pen.dev.demo.catena-x.net/api
    auth-server-url: https://centralidp-pen.dev.demo.catena-x.net/auth
    realm: CX-Central
    clientId: ${CLIENTID}
    clientSecret: ${CLIENTSECRET}
  security:
    createRole: add_self_descriptions
    deleteRole: delete_tech_user_management
  db:
    sd:
      collectionName: selfdescription
