apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image }}
        imagePullPolicy: "Always"
        ports:
        - containerPort: {{ .Values.portContainer }}
        env:
        - name: CLIENTID
          valueFrom: 
            secretKeyRef:
              name: avp-sdhub-secret
              key: ClientID
        - name: CLIENTSECRET
          valueFrom: 
            secretKeyRef:
              name: avp-sdhub-secret
              key: ClientSecret
        - name: USERNAME
          valueFrom: 
            secretKeyRef:
              name: avp-sdhub-secret
              key: Username
        - name: PASSWORD
          valueFrom: 
            secretKeyRef:
              name: avp-sdhub-secret
              key: Password
