apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "mongo.fullname" . }}
  labels:
    {{- include "mongo.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.persistence.storageClassName }}
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: {{ .Values.persistence.storageSize }}
  hostPath:
    path: /data/mongo
